name: Deploy
on:
  push:
   paths:
     - "src/cdk/**/*.ts"
jobs:
  Deploy:
   runs-on: ubuntu-22.04
   steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
       name: dist
       path: dist