name: Pipeline - feature branches
on:
  workflow_dispatch:
  push:
    branches:
      - feature/**
    paths:
      - src/cdk/**/*.ts
      - src/lambda/**/*.ts
      - __tests__/cdk/**/*.spec.ts
      - __tests__/lambda/**/*.spec.ts

jobs:

  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build
        run: |
          yarn install --immutable
          yarn build
      - name: Run tests
        run: yarn test
