name: CI/CD/CD
on: push
  # push:
  #   branches:
  #     - main
  #     - develop
  #   paths:
  #     - src/cdk/**/*.ts
  #     - src/lambda/**/*.ts
  #     - __tests__/cdk/**/*.spec.ts
  #     - __tests__/lambda/**/*.spec.ts
jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build
        run: |
          yarn install --immutable
          yarn build
      - name: Run tests
        run: yarn test
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
  Deploy:
    needs: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
