name: Pipeline - feature branches
on:
  push:
    branches:
      - feature/**
    paths:
      - src/cdk/**/*.ts
      - src/lambda/**/*.ts
      - __tests__/cdk/**/*.spec.ts
      - __tests__/lambda/**/*.spec.ts
jobs:

  build_workflow:
    uses: ./.github/workflows/build.yml

  test_workflow:
    needs: build_workflow
    uses: ./.github/workflow/test.yml
